<a href="https://colab.research.google.com/github/pushp0119/Pushp-UCS712/blob/main/ASSIGNMENT4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [4]:
import numpy as np
a=np.array([10,20,35,43,78,44])
for i in range(0,a.size):
  a[i]=a[i]+2
print(a)

for i in range(0,a.size):
  a[i]=a[i]*3
print(a)

for i in range(0,a.size):
  a[i]=a[i]/2
print(a)

[12 22 37 45 80 46]
[ 36  66 111 135 240 138]
[ 18  33  55  67 120  69]


Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [18]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print(np.flip(arr))

x = np.array([1,2,3,4,5,1,2,1,1,1])
val,count=np.unique(x,return_counts=True)
mfv=val[np.argmax(count)]
indices=np.where(x==mfv)[0]
print('Most frequent value',mfv)
print('Indices',indices)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
val,count=np.unique(y,return_counts=True)
mfv=val[np.argmax(count)]
indices=np.where(y==mfv)[0]
print('Most frequent value',mfv)
print('Indices',indices)

[5 4 6 3 2 1]
Most frequent value 1
Indices [0 5 7 8 9]
Most frequent value 1
Indices [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [23]:
import numpy as np
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0][1])
print(arr[2][0])

20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [31]:
import numpy as np
pushp=np.linspace(10,100,25)
print(pushp.ndim)
print(pushp.shape)
print(pushp.ndim*pushp.shape)
print(pushp.dtype)
print(pushp.nbytes)
print(pushp.reshape(25,1).swapaxes(0,1))
print(pushp.T)

1
(25,)
(25,)
float64
200
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [44]:
import numpy as np
ucs420_pushp=np.array([[10, 20, 30, 40],[50, 60, 70, 80],[90, 15, 20, 35]])
print(np.mean(ucs420_pushp))
print(np.median(ucs420_pushp))
print(np.max(ucs420_pushp))
print(np.min(ucs420_pushp))
print(np.unique(ucs420_pushp))
reshaped_ucs420_pushp=ucs420_pushp.reshape(4,3)
print(reshaped_ucs420_pushp)
resized_ucs420_pushp=np.resize(ucs420_pushp,(2,3))
print(resized_ucs420_pushp)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
